# urls.py

from django.urls import path
from .views import (
    register,
    user_login,
    UserProfileview,
    Products,
    Brandform,
    Categoryview,
    Revieww,
    Productdetailview,
    Productvariantview,
    Materialview,
    cartview,
    order,
    address,
    orderproduct,
    paymentview,
    couponview,
    promoview,
    whishlistview,
    colorview,
    sizeview,
    styleview,
    orderpromoview,
    paymentmethodview,
    shippingaddressview,
    checkoutview,
    dashboardview,
    update_view1,
    delete_view1,
    delete_view2,
    update_view2,
    update_view3,
    delete_view3,
    update_view4,
    delete_view4,
    delete_view5,
    update_view5,
    update_view6,
    delete_view6,
    delete_view7,
    update_view7,
    customerview,
    update_view8,
    delete_view8,
    search_view,
    search_view4,
    search_view3,
    search_view5,
    export_csv,
    export_excel,
    export_pdf,
    cart2,
    checkout2,
    contact,
    index,
    export_csv2,
    export_excel2,
    export_pdf2,
    login2,
    myAccount,
    productdetail,
    productlist,
)  # Import views module from the same directory

urlpatterns = [
    path("", cart2, name="cart2"),
    path("register/", register, name="register"),
    path("login/", user_login, name="login"),
    path("profile/", UserProfileview, name="profile"),
    path("products/", Products, name="products"),
    path("brands/", Brandform, name="brands"),
    path("category/", Categoryview, name="category"),
    path("review/", Revieww, name="review"),
    path("detail/", Productdetailview, name="detail"),
    path("provar/", Productvariantview, name="provar"),
    path("material/", Materialview, name="material"),
    path("order/", order, name="order"),
    path("cart/", cartview, name="cart"),
    path("address/", address, name="address"),
    path("orderpro/", orderproduct, name="orderproduct"),
    path("payment/", paymentview, name="payment"),
    path("promotion/", promoview, name="promotion"),
    path("coupon/", couponview, name="coupon"),
    path("whishlist/", whishlistview, name="whishlist"),
    path("orderpromo/", orderpromoview, name="orderpromo"),
    path("size/", sizeview, name="size"),
    path("style/", styleview, name="style"),
    path("color/", colorview, name="color"),
    path("dashboard/", dashboardview, name="dashboard"),
    path("checkout/", checkoutview, name="checkout"),
    path("paymethod/", paymentmethodview, name="paymethod"),
    path("shipaddress/", shippingaddressview, name="shipaddress"),
    path("update1/<int:id>/", update_view1, name="update1"),
    path("delete1/<int:id>/", delete_view1, name="delete1"),
    path("update2/<int:id>/", update_view2, name="update2"),
    path("delete2/<int:id>/", delete_view2, name="delete2"),
    path("update3/<int:id>/", update_view3, name="update3"),
    path("delete3/<int:id>/", delete_view3, name="delete3"),
    path("update4/<int:id>/", update_view4, name="update4"),
    path("delete4/<int:id>/", delete_view4, name="delete4"),
    path("update5/<int:id>/", update_view5, name="update5"),
    path("delete5/<int:id>/", delete_view5, name="delete5"),
    path("update6/<int:id>/", update_view6, name="update6"),
    path("delete6/<int:id>/", delete_view6, name="delete6"),
    path("update7/<int:id>/", update_view7, name="update7"),
    path("delete7/<int:id>/", delete_view7, name="delete7"),
    path("customer/", customerview, name="customer"),
    path("update8/<int:id>/", update_view8, name="update8"),
    path("delete8/<int:id>/", delete_view8, name="delete8"),
    path("search/", search_view, name="search"),
    path("search4/", search_view4, name="search4"),
    path("search3/", search_view3, name="search3"),
    path("search5/", search_view5, name="search5"),
    path("export/csv/", export_csv, name="export_csv"),
    path("export/excel/", export_excel, name="export_excel"),
    path("export/pdf/", export_pdf, name="export_pdf"),
    path("export/csv2/", export_csv2, name="export_csv2"),
    path("export/excel2/", export_excel2, name="export_excel2"),
    path("export/pdf2/", export_pdf2, name="export_pdf2"),
    # template
    path("cart2/", cart2, name="cart2"),
    path("checkout2/", checkout2, name="checkout2"),
    path("contact/", contact, name="contact"),
    path("index/", index, name="index"),
    path("login2/", login2, name="login2"),
    path("account/", myAccount, name="account"),
    path("productdetail/", productdetail, name="productdetail"),
    path("productlist/", productlist, name="productlist"),
    # Add more URLs as needed
]
