# Generated by Django 5.0.3 on 2024-05-19 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webDB', '0003_dashboard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
