# Generated by Django 5.0.3 on 2024-05-21 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webDB', '0004_alter_brand_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='profile_picture',
        ),
    ]
