# Generated by Django 5.0.3 on 2024-05-22 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webDB', '0006_alter_userprofile_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='logo',
            field=models.ImageField(default='images/default.jpg', upload_to='brands/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='images/default.jpg', upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='date_of_birth',
            field=models.DateField(default=''),
        ),
    ]
