# Generated by Django 5.0.3 on 2024-05-30 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webDB', '0009_remove_address_user_remove_cart_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
    ]
