# Generated by Django 5.0.3 on 2024-05-30 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webDB', '0010_remove_product_brand_remove_product_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
    ]
